# Menggunakan Nginx (Pengganti Apache XAMPP yang sangat cepat)
FROM nginx:alpine

# Menyalin seluruh file HTML, CSS, JS ke dalam folder publik Nginx
COPY . /usr/share/nginx/html

# Membuka port 80 untuk web browser
EXPOSE 80