version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bansos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_rahasia_dinsos
      MYSQL_DATABASE: bansos
    ports:
      - "3307:3306"
    volumes:
      - db_bansos_data:/var/lib/mysql
      - ./db/database.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: bansos_backend
    restart: always
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:password_rahasia_dinsos@db:3306/bansos
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:password_rahasia_dinsos@db:3306/bansos
      - SECRET_KEY=kunci_rahasia_pemkab_sidoarjo_2026
    ports:
      - "5000:5000"
    volumes:
      - ./backend/static/uploads:/app/static/uploads
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: bansos_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_bansos_data:
    driver: local